name: Build Flutter APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.4'
          architecture: x64

      - name: Check Flutter
        run: flutter --version

      - name: Install dependencies
        working-directory: flutter_app
        run: flutter pub get

      - name: Build APK
        working-directory: flutter_app
        run: flutter build apk --release --split-per-abi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk
          path: flutter_app/build/app/outputs/flutter-apk/*.apk
